require("plugins.colorschemes")
require("plugins.gitsigns")
require("plugins.which-key")
require("plugins.statusline")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.telescope")
